name: Tutorial
version: ${project.version}
main: me.evilterabite.tutorial.Tutorial
api-version: 1.17
authors: [ evilterabite ]
description: Tutorial plugin for Youtube
website: evilterabite.me

commands:
  ping:
    description: Replies pong
    usage: /ping
    aliases: [p, pinging]
  tutorialreload:
    description: reloads the plugin.
    usage: /reload
  configtest:
    description: test the config.
    usage: /configtest
  spawn:
      description: teleports you to spawn.
  setspawn:
      description: sets the spawn for the server.

